// ==================== 1. 情景映射表 ====================
var SCENARIO_MAP = {
  income: {
    salary: {
      name: "工资收入",
      asset: "cash",
      amount: 1,
      liability: 0,
      liabilityDir: null,
      fixedChange: 0,
      profit: 1,
    },
  },
  expense: {
    credit_buy: {
      name: "日常消费(信用卡)",
      asset: null,
      assetAmount: 0,
      liability: "short",
      liabilityDir: 1,
      fixedChange: 0,
      profit: -1,
    },
    cash_buy: {
      name: "现金消费/转账",
      asset: "cash",
      amount: -1,
      liability: 0,
      liabilityDir: null,
      fixedChange: 0,
      profit: -1,
    },
    credit_refund: {
      name: "消费退款(信用卡)",
      asset: null,
      assetAmount: 0,
      liability: "short",
      liabilityDir: -1,
      fixedChange: 0,
      profit: 1,
    },
    cash_refund: {
      name: "现金退款/转回",
      asset: "cash",
      amount: 1,
      liability: 0,
      liabilityDir: null,
      fixedChange: 0,
      profit: 1,
    },
    repay_short: {
      name: "信用卡还款（短期）",
      asset: "cash",
      amount: -1,
      liability: "short",
      liabilityDir: -1,
      fixedChange: 0,
      profit: 0,
    },
  },
  investment: {
    investment_buy: {
      name: "投资支出(买入)",
      asset: "investment",
      amount: 1,
      liability: 0,
      liabilityDir: null,
      fixedChange: 0,
      profit: 0,
    },
    investment_sell: {
      name: "本期赎回(卖出)",
      asset: "cash",
      amount: 1,
      liability: 0,
      liabilityDir: null,
      fixedChange: 0,
      profit: 0,
    },
    investment_dividend: {
      name: "投资收益(分红/亏损)",
      asset: "cash",
      amount: 1,
      liability: 0,
      liabilityDir: null,
      fixedChange: 0,
      profit: 1,
    },
  },
  fixed_asset: {
    repay_long: {
      name: "偿还贷款（长期）",
      asset: "cash",
      amount: -1,
      liability: "long",
      liabilityDir: -1,
      fixedChange: 0,
      profit: 0,
    },
    asset_increase: {
      name: "资产增加",
      asset: null,
      amount: 0,
      liability: 0,
      liabilityDir: null,
      fixedChange: 1,
      profit: 0,
    },
    add_long_loan: {
      name: "添加贷款（长期）",
      asset: "cash",
      amount: 1,
      liability: "long",
      liabilityDir: 1,
      fixedChange: 0,
      profit: 0,
    },
  },
};
